language: node_js
node_js:
- '4'
- stable
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: contact@mehdiaissani.com
  api_key:
    secure: UEokBZbWEZaGEL17GNuk5DrCQPamfwGqnSRy++NmlFYGV/NAV+NLIlHSBK/A09yJK8xH1biEq4qkZZo+gzq9QDkejK4HkIQstw0v1q7b35h10r6tQa3y3TEvu8HbkkW3tJJOiEaUBqgJL9Y4QT4txzpUFi+0WdAJjqB5DC8m3/XEgn3hNadpm6xLCrNRBp9YFoTIMURMDWnb43huuzVZDFpNBdfsCV7OKDk4l+xVorlriht1oEiNas81yodPfuQz0cE65/H+3IXVk6GLpPQodjhzJb1mwdXIkloNBzDwkkGhfYj9gK3GZE7dS78IFVuvvNBhdHMgHaJCUvnDdJ//afUkAwhR7dMAQPnPT1sn1wzdRds2biqCFRRY6zh1X4vlT5sBm/tDBW3bdoYASHW1Ti1ZyKJhXx6XfukHMeez/LWj4yu/x+fXGQT/Zylg3rWmRzz37LoCNeoLC+2wDi8PVfnE7PTTGAL4UKwOwxzrzRRqczxR3kBwWSNlEY/EPqAXN7TBliWtMntILEZ8mtkKPRCpdKCjLA2dTslmksdo/eg5PrFTbEORV0WAPBwPLhKJvIyLvFzu8igvQIqdOaVd9k7wb36J6Et2iG3su+dvUMPXh98hrGWFS9bc12fZs0R7G3+jWT3D1/cICerCiaT/BmQJpxIc1pt/Xbjd/ckbQ6I=
  on:
    tags: true
    repo: maissani/trailpack-srcdsrcon
    all_branches: true
    node: stable
